mkdir -pv CF && wget https://sharehost.hms.harvard.edu/bcmp/wagner_lab/virtualflow/Enamine-REAL-2018q12_isomers.pdbqt/CF/CFDEBE.tar -O CF/CFDEBE.tar
mkdir -pv CF && wget https://sharehost.hms.harvard.edu/bcmp/wagner_lab/virtualflow/Enamine-REAL-2018q12_isomers.pdbqt/CF/CFDEFE.tar -O CF/CFDEFE.tar
mkdir -pv CF && wget https://sharehost.hms.harvard.edu/bcmp/wagner_lab/virtualflow/Enamine-REAL-2018q12_isomers.pdbqt/CF/CFDECE.tar -O CF/CFDECE.tar
mkdir -pv CF && wget https://sharehost.hms.harvard.edu/bcmp/wagner_lab/virtualflow/Enamine-REAL-2018q12_isomers.pdbqt/CF/CFDEDE.tar -O CF/CFDEDE.tar
mkdir -pv CF && wget https://sharehost.hms.harvard.edu/bcmp/wagner_lab/virtualflow/Enamine-REAL-2018q12_isomers.pdbqt/CF/CFDDEE.tar -O CF/CFDDEE.tar
mkdir -pv CF && wget https://sharehost.hms.harvard.edu/bcmp/wagner_lab/virtualflow/Enamine-REAL-2018q12_isomers.pdbqt/CF/CFDDED.tar -O CF/CFDDED.tar
mkdir -pv CF && wget https://sharehost.hms.harvard.edu/bcmp/wagner_lab/virtualflow/Enamine-REAL-2018q12_isomers.pdbqt/CF/CFDDFE.tar -O CF/CFDDFE.tar
mkdir -pv CF && wget https://sharehost.hms.harvard.edu/bcmp/wagner_lab/virtualflow/Enamine-REAL-2018q12_isomers.pdbqt/CF/CFDDFD.tar -O CF/CFDDFD.tar
mkdir -pv CF && wget https://sharehost.hms.harvard.edu/bcmp/wagner_lab/virtualflow/Enamine-REAL-2018q12_isomers.pdbqt/CF/CFDDCE.tar -O CF/CFDDCE.tar
mkdir -pv CF && wget https://sharehost.hms.harvard.edu/bcmp/wagner_lab/virtualflow/Enamine-REAL-2018q12_isomers.pdbqt/CF/CFDDCD.tar -O CF/CFDDCD.tar
mkdir -pv CF && wget https://sharehost.hms.harvard.edu/bcmp/wagner_lab/virtualflow/Enamine-REAL-2018q12_isomers.pdbqt/CF/CFDDDE.tar -O CF/CFDDDE.tar
mkdir -pv CF && wget https://sharehost.hms.harvard.edu/bcmp/wagner_lab/virtualflow/Enamine-REAL-2018q12_isomers.pdbqt/CF/CFDDDD.tar -O CF/CFDDDD.tar
mkdir -pv CF && wget https://sharehost.hms.harvard.edu/bcmp/wagner_lab/virtualflow/Enamine-REAL-2018q12_isomers.pdbqt/CF/CFDDBE.tar -O CF/CFDDBE.tar
mkdir -pv CF && wget https://sharehost.hms.harvard.edu/bcmp/wagner_lab/virtualflow/Enamine-REAL-2018q12_isomers.pdbqt/CF/CFDDBD.tar -O CF/CFDDBD.tar
mkdir -pv CF && wget https://sharehost.hms.harvard.edu/bcmp/wagner_lab/virtualflow/Enamine-REAL-2018q12_isomers.pdbqt/CF/CFCEAE.tar -O CF/CFCEAE.tar
mkdir -pv CF && wget https://sharehost.hms.harvard.edu/bcmp/wagner_lab/virtualflow/Enamine-REAL-2018q12_isomers.pdbqt/CF/CFCEDE.tar -O CF/CFCEDE.tar
mkdir -pv CF && wget https://sharehost.hms.harvard.edu/bcmp/wagner_lab/virtualflow/Enamine-REAL-2018q12_isomers.pdbqt/CF/CFCEDD.tar -O CF/CFCEDD.tar
mkdir -pv CF && wget https://sharehost.hms.harvard.edu/bcmp/wagner_lab/virtualflow/Enamine-REAL-2018q12_isomers.pdbqt/CF/CFCEED.tar -O CF/CFCEED.tar
mkdir -pv CF && wget https://sharehost.hms.harvard.edu/bcmp/wagner_lab/virtualflow/Enamine-REAL-2018q12_isomers.pdbqt/CF/CFCEBE.tar -O CF/CFCEBE.tar
mkdir -pv CF && wget https://sharehost.hms.harvard.edu/bcmp/wagner_lab/virtualflow/Enamine-REAL-2018q12_isomers.pdbqt/CF/CFCEBD.tar -O CF/CFCEBD.tar
mkdir -pv CF && wget https://sharehost.hms.harvard.edu/bcmp/wagner_lab/virtualflow/Enamine-REAL-2018q12_isomers.pdbqt/CF/CFCECD.tar -O CF/CFCECD.tar
mkdir -pv CF && wget https://sharehost.hms.harvard.edu/bcmp/wagner_lab/virtualflow/Enamine-REAL-2018q12_isomers.pdbqt/CF/CFCECE.tar -O CF/CFCECE.tar
mkdir -pv CF && wget https://sharehost.hms.harvard.edu/bcmp/wagner_lab/virtualflow/Enamine-REAL-2018q12_isomers.pdbqt/CF/CFCEFD.tar -O CF/CFCEFD.tar
mkdir -pv CF && wget https://sharehost.hms.harvard.edu/bcmp/wagner_lab/virtualflow/Enamine-REAL-2018q12_isomers.pdbqt/CF/CFCDBD.tar -O CF/CFCDBD.tar
mkdir -pv CF && wget https://sharehost.hms.harvard.edu/bcmp/wagner_lab/virtualflow/Enamine-REAL-2018q12_isomers.pdbqt/CF/CFCDBE.tar -O CF/CFCDBE.tar
mkdir -pv CF && wget https://sharehost.hms.harvard.edu/bcmp/wagner_lab/virtualflow/Enamine-REAL-2018q12_isomers.pdbqt/CF/CFCDCE.tar -O CF/CFCDCE.tar
mkdir -pv CF && wget https://sharehost.hms.harvard.edu/bcmp/wagner_lab/virtualflow/Enamine-REAL-2018q12_isomers.pdbqt/CF/CFCDCD.tar -O CF/CFCDCD.tar
mkdir -pv CF && wget https://sharehost.hms.harvard.edu/bcmp/wagner_lab/virtualflow/Enamine-REAL-2018q12_isomers.pdbqt/CF/CFCDAE.tar -O CF/CFCDAE.tar
mkdir -pv CF && wget https://sharehost.hms.harvard.edu/bcmp/wagner_lab/virtualflow/Enamine-REAL-2018q12_isomers.pdbqt/CF/CFCDAD.tar -O CF/CFCDAD.tar
mkdir -pv CF && wget https://sharehost.hms.harvard.edu/bcmp/wagner_lab/virtualflow/Enamine-REAL-2018q12_isomers.pdbqt/CF/CFCDFD.tar -O CF/CFCDFD.tar
mkdir -pv CF && wget https://sharehost.hms.harvard.edu/bcmp/wagner_lab/virtualflow/Enamine-REAL-2018q12_isomers.pdbqt/CF/CFCDFE.tar -O CF/CFCDFE.tar
mkdir -pv CF && wget https://sharehost.hms.harvard.edu/bcmp/wagner_lab/virtualflow/Enamine-REAL-2018q12_isomers.pdbqt/CF/CFCDDD.tar -O CF/CFCDDD.tar
mkdir -pv CF && wget https://sharehost.hms.harvard.edu/bcmp/wagner_lab/virtualflow/Enamine-REAL-2018q12_isomers.pdbqt/CF/CFCDDE.tar -O CF/CFCDDE.tar
mkdir -pv CF && wget https://sharehost.hms.harvard.edu/bcmp/wagner_lab/virtualflow/Enamine-REAL-2018q12_isomers.pdbqt/CF/CFCDEE.tar -O CF/CFCDEE.tar
mkdir -pv CF && wget https://sharehost.hms.harvard.edu/bcmp/wagner_lab/virtualflow/Enamine-REAL-2018q12_isomers.pdbqt/CF/CFCDED.tar -O CF/CFCDED.tar
